name: 'setup-bin'
description: cache and install a binary to $PATH
author: supplypike
inputs:
  uri:
    required: true
    description: download link for binary
  name:
    required: true
    description: name of binary
  version:
    required: true
    description: version of binary
runs:
  using: 'node12'
  main: 'dist/index.js'
